# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb6c3d379db78cb48612c124c20f4d4ef9a951d9c7a2c7f7479583e3c1fcdc602996e23328b38a02c08c24f7a65efc4176fc9b636415aad773f89b4417401dfd

test:
  secret_key_base: 475336c56a0ce75ed909a5d07e43f773c69c537eaf2e6192c7af03a406d60f4d7efa7240fde7b0afbac45111531e4616d45be979a110f72618c6afa55159049e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
